// Demo catalog used by scripts/seed.mjs. Every product's name, color and
// description is written to match the actual Unsplash photos it uses
// (photos are free to use under the Unsplash License and hotlinked from
// images.unsplash.com). `photos` are Unsplash photo ids.

export const UNSPLASH = (id, w = 900, h = 1200) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&crop=entropy&auto=format&q=80`;

// Shared detail blocks per product type - combined with each product's own
// description so every product page has fabric, fit, care and styling info.
export const TYPES = {
  maxi: {
    fit: "Relaxed fit, falls to the ankle. Model is 5'7\" and wears size S.",
    care: "Gentle machine wash cold, dry in shade, warm iron on reverse.",
    highlights: ["Floor-sweeping maxi length", "Adjustable straps / easy pull-on fit", "Lightweight, breathable fabric"],
  },
  midi: {
    fit: "True to size, falls below the knee. Model is 5'6\" and wears size S.",
    care: "Gentle machine wash cold, do not tumble dry, warm iron.",
    highlights: ["Flattering midi length", "Concealed side zip", "Soft lining for all-day comfort"],
  },
  sundress: {
    fit: "Easy, relaxed fit with a flowy skirt. Model is 5'6\" and wears size S.",
    care: "Machine wash cold with similar colors, line dry.",
    highlights: ["Breathable summer-weight fabric", "Easy to style with sandals or sneakers", "Pockets at the side seams"],
  },
  gown: {
    fit: "Fitted bodice with a floor-length skirt. Size up if between sizes. Model is 5'8\" and wears size S.",
    care: "Dry clean only. Store hanging in the garment bag provided.",
    highlights: ["Floor-length evening silhouette", "Fully lined with concealed back zip", "Occasion-ready finish"],
  },
  party: {
    fit: "Close, body-skimming fit. Model is 5'7\" and wears size S.",
    care: "Hand wash cold or dry clean. Do not wring or tumble dry.",
    highlights: ["Statement party-ready design", "Stretch lining for movement", "Invisible back zip"],
  },
  blouse: {
    fit: "Regular fit, hip length. Model is 5'6\" and wears size S.",
    care: "Hand wash cold or gentle machine wash, cool iron.",
    highlights: ["Soft, fluid drape", "Easy to dress up or down", "Tuck-in or wear loose"],
  },
  shirt: {
    fit: "Classic regular fit with a straight hem. Model is 5'6\" and wears size S.",
    care: "Machine wash warm, tumble dry low, medium iron.",
    highlights: ["Button-down front", "Breathable woven fabric", "Office-to-weekend staple"],
  },
  crop: {
    fit: "Cropped, slim fit - sits at the natural waist. Model is 5'6\" and wears size S.",
    care: "Machine wash cold, dry flat to keep the shape.",
    highlights: ["Cropped length pairs with high-rise bottoms", "Soft stretch cotton", "Everyday comfort"],
  },
  tank: {
    fit: "Slim, ribbed fit. Model is 5'6\" and wears size S.",
    care: "Machine wash cold, tumble dry low.",
    highlights: ["Ribbed stretch knit", "Perfect layering piece", "Holds its shape wash after wash"],
  },
  saree: {
    fit: "Free size. Saree length 5.5 m plus 0.8 m unstitched blouse piece.",
    care: "Dry clean only. Store folded in a muslin cloth, refold every few months.",
    highlights: ["Includes unstitched blouse piece", "Rich woven pallu", "Ready for festive and wedding occasions"],
  },
  lehenga: {
    fit: "Semi-stitched lehenga (waist adjustable up to 42\"), stitched choli with margin to alter, 2.3 m dupatta.",
    care: "Dry clean only. Store the lehenga flat or rolled - never fold the embroidered panels.",
    highlights: ["3-piece set: lehenga, choli and dupatta", "Hand-finished embroidery", "Can-can lining for flare"],
  },
  kurta: {
    fit: "Straight, regular fit. Kurta length 44\". Model is 5'6\" and wears size S.",
    care: "Hand wash cold separately (colors may bleed in the first wash), dry in shade.",
    highlights: ["Breathable, everyday-comfortable fabric", "Side slits for easy movement", "Pairs with palazzos, pants or jeans"],
  },
  kurtaSet: {
    fit: "Kurta, bottom and dupatta set. Regular fit. Model is 5'6\" and wears size S.",
    care: "Hand wash cold separately, dry in shade, iron on reverse.",
    highlights: ["Complete coordinated set", "Elasticated, comfortable waistband", "Lightweight dupatta included"],
  },
  bag: {
    fit: "Dimensions: approx. 28 cm (W) x 22 cm (H) x 12 cm (D). Detachable strap included.",
    care: "Wipe clean with a soft dry cloth. Stuff with paper and store in the dust bag provided.",
    highlights: ["Structured shape with zip closure", "Inner zip and slip pockets", "Fits phone, wallet and essentials"],
  },
  tote: {
    fit: "Dimensions: approx. 38 cm (W) x 35 cm (H) x 12 cm (D). Shoulder drop 25 cm.",
    care: "Spot clean with a damp cloth. Air dry.",
    highlights: ["Roomy enough for a laptop or daily essentials", "Reinforced shoulder handles", "Inner slip pocket"],
  },
  clutch: {
    fit: "Dimensions: approx. 24 cm (W) x 14 cm (H). Optional chain strap included.",
    care: "Wipe gently with a soft dry cloth. Store in the dust bag provided.",
    highlights: ["Evening-ready design", "Magnetic snap closure", "Fits a phone, cards and lipstick"],
  },
  earrings: {
    fit: "Lightweight and comfortable for all-day wear. Push-back closure.",
    care: "Avoid contact with water, perfume and lotions. Store in the pouch provided.",
    highlights: ["Hypoallergenic, nickel-free posts", "Anti-tarnish coating", "Gift-ready packaging"],
  },
  necklace: {
    fit: "Chain length 45 cm with a 5 cm extender. Lobster-claw clasp.",
    care: "Avoid contact with water, perfume and lotions. Store flat in the pouch provided.",
    highlights: ["Anti-tarnish finish", "Adjustable length", "Gift-ready packaging"],
  },
  bracelet: {
    fit: "Fits wrists 15-18 cm. Adjustable clasp.",
    care: "Remove before bathing or swimming. Wipe with a soft cloth.",
    highlights: ["Adjustable fit", "Stackable design", "Gift-ready packaging"],
  },
  sunglasses: {
    fit: "Lens width 52 mm, bridge 20 mm, temple 145 mm. Medium fit.",
    care: "Clean with the microfiber cloth provided. Store in the hard case when not in use.",
    highlights: ["100% UV400 protection", "Scratch-resistant lenses", "Hard case and cleaning cloth included"],
  },
  belt: {
    fit: "Width 3 cm. Fits waist 26\"-36\" with 5 adjustment holes.",
    care: "Wipe with a dry cloth. Condition leather occasionally to keep it supple.",
    highlights: ["Genuine leather", "Polished metal buckle", "Works with jeans, trousers and dresses"],
  },
  scarf: {
    fit: "Dimensions: 180 cm x 70 cm.",
    care: "Hand wash cold or dry clean. Cool iron.",
    highlights: ["Soft, lightweight drape", "Wear as a scarf, stole or head wrap", "Rolled, hand-finished edges"],
  },
};

const C = {
  black: { name: "Black", hex: "#111111" },
  red: { name: "Red", hex: "#B3122E" },
  crimson: { name: "Crimson", hex: "#9E1B32" },
  maroon: { name: "Maroon", hex: "#6B1E2E" },
  ivory: { name: "Ivory", hex: "#F5F0E6" },
  white: { name: "White", hex: "#FFFFFF" },
  pink: { name: "Pink", hex: "#E8A0B4" },
  blush: { name: "Blush Pink", hex: "#F2C4CE" },
  yellow: { name: "Yellow", hex: "#F2C230" },
  mustard: { name: "Mustard", hex: "#D4A017" },
  orange: { name: "Orange", hex: "#E0712C" },
  green: { name: "Green", hex: "#2E7D4F" },
  emerald: { name: "Emerald", hex: "#1E6B4F" },
  olive: { name: "Olive", hex: "#6B7B3A" },
  blue: { name: "Blue", hex: "#2F5DA8" },
  navy: { name: "Navy", hex: "#1F2A44" },
  skyBlue: { name: "Sky Blue", hex: "#8EC5E8" },
  purple: { name: "Purple", hex: "#6A3D8F" },
  grey: { name: "Grey", hex: "#8A8A8A" },
  silver: { name: "Silver", hex: "#C0C0C0" },
  gold: { name: "Gold", hex: "#C9A227" },
  tan: { name: "Tan", hex: "#B5835A" },
  brown: { name: "Brown", hex: "#6F4E37" },
  cream: { name: "Cream", hex: "#EFE6D2" },
  leopard: { name: "Leopard Print", hex: "#B8864B" },
  multi: { name: "Multicolor", hex: "#C06C84" },
};

// [slug, name, type, photos, colors, material, brand, price, compareAtPrice, description]
export const CATALOG = {
  Dresses: [
    ["crimson-floral-strappy-maxi-dress", "Crimson Floral Strappy Maxi Dress", "maxi", ["photo-1600102427329-d5b2cde7e162"], [C.black, C.red], "100% Viscose", "Bloom & Co", 2499, 3299,
      "A romantic black maxi dress scattered with red and white blooms. Delicate spaghetti straps, a softly gathered waist and a floaty skirt make it the dress you'll reach for on every warm-weather getaway."],
    ["wildflower-tiered-midi-dress", "Wildflower Tiered Midi Dress", "midi", ["photo-1602010069450-0a62034f235c"], [C.black], "Viscose Crepe", "Bloom & Co", 2199, 2799,
      "Wildflowers in red and white bloom across a dark base on this tiered midi. The gentle tiers add movement with every step - wear it with sandals for brunch or ankle boots when the weather turns."],
    ["rose-garden-floral-dress", "Rose Garden Floral Dress", "sundress", ["photo-1502868354157-ec2edd2a1651"], [C.ivory, C.red], "Cotton Voile", "Lumière", 1899, 2399,
      "A fresh ivory dress printed with red roses, cut from airy cotton voile. Short sleeves and a relaxed skirt keep it easy and effortless from morning to evening."],
    ["pastel-blossom-sundress", "Pastel Blossom Sundress", "sundress", ["photo-1592924514972-71c5938462d1"], [C.pink], "Cotton Blend", "Bloom & Co", 1699, 2199,
      "Soft pink and white blossoms on a light, breathable sundress. The fitted bodice and swingy skirt make it a sweet pick for day dates, picnics and holidays."],
    ["meadow-floral-sundress", "Meadow Floral Sundress", "sundress", ["photo-1762154057377-cc9d3dd6900c"], [C.multi], "Rayon", "Lumière", 1799, null,
      "A cheerful all-over floral sundress with a flattering sweetheart neckline. Made from silky rayon that keeps you cool through the hottest afternoons."],
    ["riviera-seaside-maxi-dress", "Riviera Seaside Maxi Dress", "maxi", ["photo-1496747611176-843222e1e57c"], [C.multi], "Viscose Georgette", "Aura", 2799, 3499,
      "Made for sea breezes and golden hour. This flowing printed maxi moves beautifully in the wind - pair it with a woven bag and flat sandals for the perfect resort look."],
    ["olive-long-sleeve-maxi-dress", "Olive Long-Sleeve Maxi Dress", "maxi", ["photo-1609357605129-26f69add5d6e"], [C.olive], "Crinkle Cotton", "Aura", 2599, null,
      "An earthy olive-green maxi with full sleeves and a softly defined waist. The crinkle cotton needs no ironing, making it a go-to for travel and long days out."],
    ["sunflower-floral-wrap-dress", "Sunflower Floral Wrap Dress", "midi", ["photo-1676327478489-ae4f973d0bbe"], [C.yellow, C.blue], "Viscose", "Bloom & Co", 2299, 2899,
      "Bright yellow and blue florals on a true wrap silhouette that ties at the waist. Adjust the wrap for your perfect fit - a feel-good dress for sunny days."],
    ["high-slit-floral-wrap-dress", "High-Slit Floral Wrap Dress", "maxi", ["photo-1759992878336-a5dd342ea245"], [C.multi], "Satin Finish Polyester", "Lumière", 2999, 3799,
      "A show-stopping floral wrap dress with a daring high slit and a plunging V-neck. The satin finish catches the light - perfect for weddings, parties and date nights."],
    ["leopard-print-slip-midi-dress", "Leopard Print Slip Midi Dress", "midi", ["photo-1772456595241-36700f9c4981"], [C.leopard], "Satin", "Aura", 2399, null,
      "The ultimate city-chic slip dress in a bold leopard print. Wear it alone on warm days or layer with a tee and blazer for off-duty style."],
    ["dove-grey-floral-party-dress", "Dove Grey Floral Party Dress", "party", ["photo-1582533561751-ef6f6ab93a2e", "photo-1582533575066-75bd83ac91de"], [C.grey], "Georgette", "Lumière", 2699, 3399,
      "Understated elegance in dove grey with a subtle floral pattern. Long sleeves and a graceful flared hem make it perfect for cocktail parties and evening functions."],
    ["midnight-blue-floral-dress", "Midnight Blue Floral Dress", "party", ["photo-1617258856138-402b60da4e2a"], [C.navy], "Georgette", "Bloom & Co", 2499, 2999,
      "A deep blue dress sprinkled with delicate florals. Its fitted waist and fluid skirt create a timeless, feminine silhouette for evenings out."],
    ["tangerine-long-sleeve-dress", "Tangerine Long-Sleeve Dress", "midi", ["photo-1622080159549-11537bf939e6"], [C.orange], "Crepe", "Aura", 2199, null,
      "A vibrant tangerine midi with long sleeves and a clean, modern cut. A single-color statement that needs nothing more than gold jewellery and nude heels."],
    ["champagne-sparkle-mini-dress", "Champagne Sparkle Mini Dress", "party", ["photo-1772615071677-6441340349fd"], [C.silver], "Sequined Mesh", "Lumière", 3499, 4499,
      "Head-to-toe sparkle for when it's time to celebrate. This sequinned mini is fully lined for comfort and made to dance in all night long."],
    ["starlight-sequin-evening-dress", "Starlight Sequin Evening Dress", "gown", ["photo-1779763320502-e343cfa86cdc"], [C.gold], "Sequined Georgette", "Lumière", 4299, 5499,
      "Hand-placed sequins shimmer across this elegant evening dress. A flattering neckline and fluid drape make it the one for receptions and formal galas."],
    ["amethyst-shimmer-slit-gown", "Amethyst Shimmer Slit Gown", "gown", ["photo-1765871422437-dcc4393b2b33"], [C.purple], "Metallic Knit", "Lumière", 4499, 5999,
      "A sparkling purple gown with a dramatic thigh-high slit. The metallic knit hugs your curves and catches every light - pure red-carpet glamour."],
    ["onyx-shimmer-evening-gown", "Onyx Shimmer Evening Gown", "gown", ["photo-1765871421824-f06af71a4650"], [C.black], "Metallic Knit", "Lumière", 4499, null,
      "A shimmering dark gown with a sleek, body-skimming shape. Subtle sparkle and a floor-length hem make it an elegant choice for black-tie evenings."],
    ["classic-little-black-dress", "Classic Little Black Dress", "party", ["photo-1623580674393-edf6eb7090f8"], [C.black], "Stretch Crepe", "Aura", 1999, 2599,
      "Every wardrobe needs one. This sleeveless little black dress has clean lines and a flattering fit that works for dinners, parties and everything in between."],
    ["maroon-velvet-evening-gown", "Maroon Velvet Evening Gown", "gown", ["photo-1568252542512-9fe8fe9c87bb"], [C.maroon], "Stretch Velvet", "Lumière", 3999, 4999,
      "A rich maroon velvet gown with a sophisticated silhouette. Soft to the touch with a luxurious sheen - made for winter weddings and festive evenings."],
    ["scarlet-evening-gown", "Scarlet Evening Gown", "gown", ["photo-1583039949165-96ee24b0d8de"], [C.red], "Satin", "Lumière", 3799, 4799,
      "Make an entrance in bold scarlet. A fitted bodice flows into a floor-length satin skirt for a classic, head-turning evening look."],
    ["silver-glitter-gown", "Silver Glitter Gown", "gown", ["photo-1547697933-66bcb20f114a"], [C.silver], "Glitter Tulle", "Lumière", 4999, 6499,
      "A dreamy grey glitter gown with layers of sparkling tulle. Fairytale-worthy for engagements, cocktail receptions and special celebrations."],
    ["black-gold-cocktail-dress", "Black & Gold Cocktail Dress", "party", ["photo-1610209740880-6ecc4b20ea78"], [C.black, C.gold], "Embroidered Net", "Aura", 3299, 3999,
      "Gold embroidery on a black sleeveless base gives this cocktail dress a regal edge. Pair it with statement earrings for festive parties."],
    ["lemon-sleeveless-sundress", "Lemon Sleeveless Sundress", "sundress", ["photo-1609695813802-3c443be34359"], [C.yellow], "Cotton", "Bloom & Co", 1499, 1899,
      "Sunshine in a dress. This sleeveless yellow sundress in soft cotton is light, bright and made for long summer days outdoors."],
    ["blue-white-striped-sundress", "Blue & White Sleeveless Sundress", "sundress", ["photo-1613966570650-add3cf83aa83"], [C.blue, C.white], "Cotton Linen", "Lumière", 1699, null,
      "A crisp blue-and-white sundress that's pure holiday. Pair it with a straw hat and sandals for beach walks and seaside lunches."],
    ["white-lace-beach-dress", "White Lace Beach Dress", "sundress", ["photo-1593105522065-9a6ecd21aeb2"], [C.white], "Cotton Lace", "Bloom & Co", 2299, 2799,
      "Delicate white lace with a breezy, feminine shape. Perfect for beach vacations, sundowners and summer celebrations."],
    ["red-plaid-shirt-dress", "Red Plaid Shirt Dress", "midi", ["photo-1582738509941-360b28c941ea"], [C.red, C.white], "Brushed Cotton", "Aura", 1899, null,
      "A classic white-and-red plaid dress with a relaxed shirt-style bodice. Cinch it with a belt and add a hat for an easy, put-together weekend look."],
    ["backless-black-maxi-dress", "Backless Black Maxi Dress", "gown", ["photo-1751284520724-a71abbaa1255"], [C.black], "Stretch Jersey", "Aura", 2799, 3499,
      "Simple from the front, stunning from the back. A daring open back and a sleek maxi length make this black jersey dress an instant evening favourite."],
  ],
  "Tops & Blouses": [
    ["ruby-satin-blouse", "Ruby Satin Blouse", "blouse", ["photo-1761117228880-df2425bd70da", "photo-1761121317492-57feee4fc674"], [C.red], "Satin", "Everyday Muse", 1299, 1699,
      "A luxurious ruby-red satin blouse with a soft sheen and fluid drape. Tuck it into tailored trousers for work, or wear with jeans and a statement necklace for evenings."],
    ["tropical-floral-print-blouse", "Tropical Floral Print Blouse", "blouse", ["photo-1764337593519-c51a77b4fc3d"], [C.multi], "Rayon", "Everyday Muse", 1099, 1399,
      "Vivid tropical florals bring instant energy to this easy, relaxed blouse. Lightweight rayon keeps it comfortable in the heat."],
    ["crisp-white-button-up-shirt", "Crisp White Button-Up Shirt", "shirt", ["photo-1611235116156-0cbda6649efb"], [C.white], "100% Cotton Poplin", "Aura", 1199, null,
      "The perfect white shirt: crisp cotton poplin, a sharp collar and a clean, tailored cut. Wear it buttoned up, knotted at the waist or open over a tank."],
    ["white-linen-relaxed-shirt", "White Linen Relaxed Shirt", "shirt", ["photo-1604182440345-4a82e1c3876b"], [C.white], "Pure Linen", "Aura", 1599, 1999,
      "Breathable pure linen in a slightly oversized fit. It softens with every wash and looks effortlessly polished with black trousers."],
    ["white-cotton-crop-top", "White Cotton Crop Top", "crop", ["photo-1673925205809-601b5a22eb61", "photo-1673999707565-8bb553c9765b"], [C.white], "Cotton Spandex", "Everyday Muse", 699, 899,
      "A clean white crop top in soft stretch cotton. The easiest base layer for high-waisted jeans, skirts and co-ords."],
    ["essential-white-crop-tee", "Essential White Crop Tee", "crop", ["photo-1548389995-fbd3151a501f"], [C.white], "100% Cotton", "Everyday Muse", 599, null,
      "Your everyday cropped tee with a relaxed crew neck. Soft, breathable and endlessly versatile."],
    ["floral-cropped-top", "Floral Cropped Top", "crop", ["photo-1564257631407-4deb1f99d992"], [C.white, C.multi], "Cotton", "Bloom & Co", 799, 999,
      "A white cropped top with a pretty multicolor floral print. Pair with denim shorts for festivals and summer outings."],
    ["striped-long-sleeve-tee", "Striped Long-Sleeve Tee", "blouse", ["photo-1530981785497-a62037228fe9"], [C.grey, C.black], "Cotton Jersey", "Everyday Muse", 899, null,
      "A Breton-inspired grey and black striped tee with long sleeves. A timeless layering staple for cooler days."],
    ["black-ribbed-tank-top", "Black Ribbed Tank Top", "tank", ["photo-1620062161349-7abc66286084"], [C.black], "Ribbed Cotton Stretch", "Everyday Muse", 499, 699,
      "A figure-hugging black ribbed tank that goes with everything. Wear alone or layer under shirts and blazers."],
    ["white-ribbed-tank-top", "White Ribbed Tank Top", "tank", ["photo-1620062213761-9af24c959624"], [C.white], "Ribbed Cotton Stretch", "Everyday Muse", 499, 699,
      "The white version of our best-selling ribbed tank. Soft, stretchy and opaque - a true wardrobe essential."],
    ["heart-print-blue-shirt", "Heart Print Blue Shirt", "shirt", ["photo-1596755094514-f87e34085b2c"], [C.blue], "Cotton", "Bloom & Co", 1299, 1599,
      "A playful blue button-down scattered with tiny white hearts. Fun enough for weekends, polished enough for casual Fridays."],
    ["chambray-button-down-shirt", "Chambray Button-Down Shirt", "shirt", ["photo-1626497764746-6dc36546b388"], [C.skyBlue], "Cotton Chambray", "Aura", 1399, null,
      "Classic light-blue chambray with a soft, lived-in feel. Wear it tucked, tied or layered open over a dress."],
    ["blue-striped-oxford-shirt", "Blue Striped Oxford Shirt", "shirt", ["photo-1589810635657-232948472d98"], [C.blue, C.white], "Cotton Oxford", "Aura", 1399, 1799,
      "A crisp blue-and-white striped shirt in structured oxford cotton. A smart pick for the office that also looks great with denim."],
    ["paisley-print-shirt", "Paisley Print Shirt", "shirt", ["photo-1766471524299-016b52512780"], [C.multi], "Viscose", "Bloom & Co", 1299, null,
      "Bold, colorful paisley on a relaxed, flowy shirt. A standout piece for holidays and brunches."],
    ["bow-tie-floral-blouse", "Bow Tie Floral Blouse", "blouse", ["photo-1763559053411-80ae3727443e"], [C.multi], "Georgette", "Everyday Muse", 1199, 1499,
      "A feminine floral blouse with a tie-neck bow. Soft georgette drapes gracefully - tuck into a skirt for a vintage-inspired look."],
    ["mocha-utility-shirt", "Mocha Utility Shirt", "shirt", ["photo-1760551600405-54c70e6d7f42", "photo-1760551601753-9bc58cecdb4f"], [C.brown], "Cotton Twill", "Aura", 1499, 1899,
      "A mocha-brown utility shirt with a relaxed fit and a soft twill finish. Style it with jeans for an easy, earthy everyday look."],
    ["red-ruched-satin-top", "Red Ruched Satin Top", "blouse", ["photo-1783159143477-7c027bf65772"], [C.red], "Satin", "Everyday Muse", 1099, 1399,
      "A glossy red satin top with flattering ruching through the body. Pair with black trousers or a skirt for parties and dinners."],
    ["white-sleeveless-shirt", "White Sleeveless Shirt", "shirt", ["photo-1770294758906-c8762abb2c8b"], [C.white], "Cotton Poplin", "Aura", 999, null,
      "A sleeveless take on the classic white shirt. Cool, crisp and perfect for hot summer days in the city."],
  ],
  "Ethnic Wear": [
    ["royal-purple-banarasi-silk-saree", "Royal Purple Banarasi Silk Saree", "saree", ["photo-1641699862936-be9f49b1c38d"], [C.purple, C.gold], "Banarasi Silk", "Heritage Loom", 7999, 10999,
      "A regal purple Banarasi silk saree with intricate gold zari weaving along the border and a richly woven pallu. An heirloom-worthy drape for weddings and festive celebrations."],
    ["maroon-rust-silk-saree", "Maroon & Rust Silk Saree", "saree", ["photo-1610030469983-98e550d6193c", "photo-1610030469839-f909584b43f1"], [C.maroon, C.brown], "Art Silk", "Rangmahal", 3499, 4499,
      "Warm maroon and rust tones come together in this elegant silk saree with a contrast border. Lightweight and easy to drape - ideal for pujas, family functions and festive dinners."],
    ["blue-mustard-silk-saree", "Blue & Mustard Silk Saree", "saree", ["photo-1610189012906-4c0aa9b9781e"], [C.blue, C.mustard], "Soft Silk", "Heritage Loom", 4299, 5299,
      "Rich royal blue paired with a mustard-yellow border and pallu. The soft silk drapes fluidly and is comfortable to wear all day at celebrations."],
    ["emerald-green-kanjivaram-saree", "Emerald Green Silk Saree", "saree", ["photo-1679006831648-7c9ea12e5807"], [C.emerald, C.gold], "Pure Silk", "Heritage Loom", 8999, 11999,
      "A lustrous emerald-green silk saree with a gold woven border. Pair with temple jewellery for a classic South Indian bridal-guest look."],
    ["sunset-pink-orange-saree", "Sunset Pink & Orange Saree", "saree", ["photo-1617627143750-d86bc21e42bb"], [C.pink, C.orange], "Silk Blend", "Rangmahal", 3999, 4999,
      "Vibrant pink and orange blend like a sunset in this festive silk-blend saree, finished with a gold border. A joyful pick for mehendi, haldi and Diwali."],
    ["ivory-red-bengal-saree", "Ivory & Red Bengal Saree", "saree", ["photo-1678705730064-a7ecbab4b3fb"], [C.ivory, C.red], "Cotton Silk", "Heritage Loom", 2999, 3799,
      "Inspired by the traditional Bengali laal-paar saree - ivory drape with a bold red border. Made for Durga Puja, festivals and cultural occasions."],
    ["yellow-blue-cotton-saree", "Yellow & Blue Cotton Saree", "saree", ["photo-1706943262454-84ee74854346"], [C.yellow, C.blue], "Handloom Cotton", "Rangmahal", 1999, 2499,
      "A breezy handloom cotton saree in sunny yellow with a blue border. Soft, breathable and perfect for daytime events and office festivities."],
    ["red-gold-bridal-silk-saree", "Red & Gold Bridal Silk Saree", "saree", ["photo-1617633150878-7df1d12a9a57"], [C.red, C.gold], "Banarasi Silk", "Heritage Loom", 9999, 13999,
      "A traditional bridal red Banarasi silk saree densely woven with gold zari motifs. Timeless, auspicious and made for your most special day."],
    ["green-gold-festive-saree", "Green & Gold Festive Saree", "saree", ["photo-1611106211090-8f3c79eb8552"], [C.green, C.gold], "Silk Blend", "Rangmahal", 4999, 6499,
      "A festive green saree with a heavy gold border and pallu. Rich, celebratory and perfect for weddings, sangeet nights and festival gatherings."],
    ["sapphire-red-lehenga-choli", "Sapphire & Red Lehenga Choli", "lehenga", ["photo-1640745690917-41cacbf557c3", "photo-1640745690845-4d6aa890811d", "photo-1640745690911-d4a19edc67ce"], [C.blue, C.red], "Silk with Zari Embroidery", "Aura Ethnic", 12999, 16999,
      "A striking sapphire-blue lehenga with a contrast red dupatta and fine zari embroidery. The flared skirt swirls beautifully - a statement for weddings and receptions."],
    ["crimson-bridal-lehenga", "Crimson Bridal Lehenga", "lehenga", ["photo-1645856048803-51971c462707", "photo-1645856049235-8464376187fa", "photo-1645856049199-3a631389c2d4"], [C.crimson, C.gold], "Raw Silk with Hand Embroidery", "Aura Ethnic", 18999, 24999,
      "A classic crimson bridal lehenga with gold embroidery and a sheer net dupatta. Generous flare, rich detailing and a timeless silhouette for the bride."],
    ["rose-pink-flared-lehenga", "Rose Pink Flared Lehenga", "lehenga", ["photo-1645856048928-ceba2c740855"], [C.pink, C.red], "Georgette", "Aura Ethnic", 9999, 12999,
      "A red and rose-pink lehenga with a sweeping flared skirt. Light georgette keeps it easy to dance in at sangeet and mehendi ceremonies."],
    ["maroon-embroidered-lehenga", "Maroon Embroidered Lehenga", "lehenga", ["photo-1756483488645-5973a1a92e33"], [C.maroon], "Velvet with Zardozi Work", "Aura Ethnic", 15999, 19999,
      "Opulent maroon velvet with intricate zardozi embroidery. A regal, rich-toned lehenga for winter weddings and grand receptions."],
    ["emerald-embroidered-lehenga", "Emerald Embroidered Lehenga", "lehenga", ["photo-1756483510809-122c56fbb035"], [C.emerald], "Silk with Mirror & Thread Work", "Aura Ethnic", 14999, 18999,
      "Deep emerald green with ornate mirror and thread embroidery. A jewel-toned lehenga that stands out at every wedding function."],
    ["blush-pink-cape-lehenga-set", "Blush Pink Cape Lehenga Set", "lehenga", ["photo-1756483510859-c0ab4c45782c"], [C.blush], "Organza with Sequin Work", "Aura Ethnic", 13999, 17499,
      "A modern blush-pink lehenga paired with a flowing embellished cape instead of a dupatta. Contemporary and elegant for engagements and cocktail nights."],
    ["marigold-maroon-lehenga", "Marigold & Maroon Lehenga", "lehenga", ["photo-1767955694884-d4bf352c23c2"], [C.mustard, C.maroon], "Silk with Gota Patti", "Aura Ethnic", 11999, 14999,
      "Marigold yellow and maroon come together with traditional gota-patti work. Bright and festive - perfect for haldi and mehendi celebrations."],
    ["white-floral-kurta-pyjama-set", "White Floral Kurta Pyjama Set", "kurtaSet", ["photo-1745313452052-0e4e341f326c"], [C.white, C.multi], "Pure Cotton", "Rangmahal", 1899, 2499,
      "A fresh white cotton kurta and pyjama set with a delicate floral print. Breathable and comfortable - lovely for summer festivities and daily wear."],
    ["pink-floral-kurta-pant-set", "Pink Floral Kurta & Pant Set", "kurtaSet", ["photo-1741847639057-b51a25d42892"], [C.pink], "Cotton Cambric", "Rangmahal", 1999, 2599,
      "A soft pink floral kurta with matching pants. A pretty, easy-to-wear set for festive days, family visits and office celebrations."],
    ["red-kurta-floral-dupatta-set", "Red Kurta with Floral Dupatta", "kurtaSet", ["photo-1759840278381-bf7d5e332050", "photo-1759840278862-ef629e9b0f64"], [C.red], "Rayon with Printed Chiffon Dupatta", "Rangmahal", 2299, 2899,
      "A vibrant red kurta paired with a printed floral dupatta. Traditional charm with modern ease - made for festivals and family gatherings."],
    ["ocean-blue-salwar-suit", "Ocean Blue Salwar Suit", "kurtaSet", ["photo-1780247585190-343fbb738c67", "photo-1780247723311-2dae151784d1"], [C.blue], "Cotton Silk", "Heritage Loom", 2499, 3199,
      "A serene ocean-blue salwar suit with a matching dupatta. Elegant and understated for pujas, festivals and day functions."],
    ["blue-floral-tunic-kurti", "Blue Floral Tunic Kurti", "kurta", ["photo-1768289222345-64b6b53bf78b"], [C.blue, C.white], "Cotton", "Rangmahal", 1199, 1499,
      "A breezy blue floral tunic-style kurti. Perfect for everyday wear with pants, palazzos or jeans."],
    ["multicolor-printed-kurta", "Multicolor Printed Kurta", "kurta", ["photo-1769063382706-8156b3b33eac"], [C.multi], "Rayon", "Rangmahal", 1099, null,
      "A bright, colorful printed kurta that instantly lifts any day. Soft rayon, easy fit and a joyful pattern."],
    ["yellow-tiered-embroidered-kurti", "Yellow Tiered Embroidered Kurti", "kurta", ["photo-1760287363878-1a09af715b80"], [C.yellow], "Cotton with Thread Embroidery", "Heritage Loom", 1599, 1999,
      "A cheerful yellow tiered kurti with delicate embroidery at the neckline. Flowy and feminine - a lovely pick for haldi and daytime festivities."],
    ["navy-paisley-kurti", "Navy Paisley Kurti", "kurta", ["photo-1760287364219-160c234ded00"], [C.navy], "Cotton", "Heritage Loom", 1299, null,
      "A dark navy kurti with a classic paisley print. Versatile enough for work and festive days alike."],
    ["purple-tunic-striped-pant-set", "Purple Tunic & Striped Pant Set", "kurtaSet", ["photo-1760287363699-a08d553fb8a9"], [C.purple], "Cotton Blend", "Heritage Loom", 1899, 2399,
      "A purple patterned tunic paired with striped straight pants for a fresh, contemporary Indo-western look."],
  ],
  Accessories: [
    ["scarlet-leather-top-handle-bag", "Scarlet Leather Top-Handle Bag", "bag", ["photo-1584917865442-de89df76afd3"], [C.red], "Genuine Leather", "Finish Line", 2999, 3999,
      "A structured scarlet leather bag with a polished top handle. The pop of color that elevates every outfit, from office wear to evening dresses."],
    ["cognac-leather-handbag", "Cognac Leather Handbag", "bag", ["photo-1590874103328-eac38a683ce7"], [C.tan], "Genuine Leather", "Finish Line", 3299, null,
      "A timeless cognac-brown leather handbag that only gets better with age. Roomy, structured and made to go with everything."],
    ["grey-satchel-gold-buckle", "Grey Satchel with Gold Buckles", "bag", ["photo-1605733513597-a8f8341084e6"], [C.grey], "Vegan Leather", "Finish Line", 2499, 2999,
      "A sophisticated grey satchel accented with polished gold buckles. Structured and elegant for work and weekends."],
    ["noir-leather-shoulder-bag", "Noir Leather Shoulder Bag", "bag", ["photo-1614179689702-355944cd0918"], [C.black], "Genuine Leather", "Finish Line", 3499, 4299,
      "A sleek black leather shoulder bag with silver hardware. The classic everyday bag you'll carry for years."],
    ["blush-pink-mini-bag", "Blush Pink Mini Bag", "bag", ["photo-1681747685985-a401c271156c"], [C.blush], "Vegan Leather", "Gilded", 1799, 2299,
      "A sweet blush-pink mini bag for your essentials. Wear it cross-body or by the top handle for brunches, parties and weekend plans."],
    ["floral-canvas-handbag", "Floral Canvas Handbag", "bag", ["photo-1591561954557-26941169b49e"], [C.white, C.red], "Printed Canvas", "Gilded", 1499, null,
      "A white handbag with a cheerful red floral print. Lightweight and fun - perfect for summer and holidays."],
    ["tan-leather-everyday-bag", "Tan Leather Everyday Bag", "bag", ["photo-1598532163257-ae3c6b2524b6"], [C.brown], "Genuine Leather", "Finish Line", 2799, 3499,
      "A soft brown leather bag with a slouchy, relaxed shape. Spacious enough for your everyday essentials."],
    ["classic-canvas-tote", "Classic Canvas Tote", "tote", ["photo-1548863227-3af567fc3b27", "photo-1574365569389-a10d488ca3fb"], [C.white], "Heavy Cotton Canvas", "Finish Line", 699, 899,
      "A sturdy white canvas tote for groceries, books or beach days. Simple, reusable and endlessly useful."],
    ["tan-leather-clutch", "Tan Leather Clutch", "clutch", ["photo-1749294435694-ce3c586591e6", "photo-1749294435693-4f39ec7e0ab2", "photo-1749294435697-386a322bab8d"], [C.tan], "Genuine Leather", "Finish Line", 1599, 1999,
      "A minimal tan leather clutch with clean lines. Slip it under your arm for dinners or keep it in your tote as an organizer."],
    ["pearl-white-quilted-clutch", "Pearl White Quilted Clutch", "clutch", ["photo-1783700475749-6e6521a503fa", "photo-1783700475349-46e60e2c959c"], [C.white], "Quilted Vegan Leather", "Gilded", 1899, 2499,
      "A pearl-white quilted clutch with a timeless, luxe feel. Perfect for weddings, cocktail evenings and special occasions."],
    ["white-beaded-clutch", "White Beaded Clutch", "clutch", ["photo-1783700549620-a6699881dc45"], [C.white], "Glass Beads on Satin", "Gilded", 2199, 2799,
      "Hand-beaded in white on a satin base, this clutch adds subtle glamour to bridal, reception and party looks."],
    ["cream-pleated-handbag", "Cream Pleated Handbag", "bag", ["photo-1761646238176-b480909e6ba6"], [C.cream], "Pleated Vegan Leather", "Gilded", 2299, null,
      "A soft cream handbag with sculptural pleats and a curved handle. A modern, elegant piece that pairs with both western and ethnic outfits."],
    ["sapphire-drop-earrings", "Sapphire Drop Earrings", "earrings", ["photo-1535632066927-ab7c9ab60908"], [C.silver, C.blue], "Silver-Plated Brass with Cubic Zirconia", "Gilded", 1299, 1699,
      "Silver-toned drop earrings set with a brilliant blue stone. A touch of sparkle for evenings and celebrations."],
    ["twisted-gold-hoop-earrings", "Twisted Gold Hoop Earrings", "earrings", ["photo-1617038220319-276d3cfab638"], [C.gold], "18K Gold-Plated Brass", "Gilded", 899, 1199,
      "Classic gold hoops with a subtle twisted texture that catches the light. Everyday elegance you'll never take off."],
    ["red-white-enamel-earrings", "Red & White Enamel Earrings", "earrings", ["photo-1671642883395-0ab89c3ac890"], [C.red, C.white], "Enamel on Alloy", "Gilded", 699, null,
      "Playful red and white enamel earrings that add a pop of color to any outfit - especially lovely with ethnic wear."],
    ["crescent-moon-pendant-necklace-set", "Crescent Moon Pendant Necklace Set", "necklace", ["photo-1599643478518-a784e5dc4c8f"], [C.gold, C.blue], "18K Gold-Plated Brass", "Gilded", 1499, 1899,
      "A layered set of two gold necklaces - one with a blue stone pendant and one with a delicate crescent moon charm. Wear together or separately."],
    ["sapphire-pendant-necklace", "Sapphire Pendant Necklace", "necklace", ["photo-1599643477877-530eb83abc8e"], [C.silver, C.blue], "Sterling Silver with Blue Stone", "Gilded", 1799, 2299,
      "A refined silver pendant set with a deep blue stone. Understated and elegant for everyday wear or gifting."],
    ["floral-gold-chain-necklace", "Floral Gold Chain Necklace", "necklace", ["photo-1685970731571-72ede0cb26ea"], [C.gold, C.white], "Gold-Plated Brass with Enamel", "Gilded", 1299, null,
      "A dainty gold chain adorned with tiny white flowers. Romantic and feminine - perfect with summer dresses."],
    ["silver-heart-pendant-necklace", "Silver Heart Pendant Necklace", "necklace", ["photo-1589128777073-263566ae5e4d"], [C.silver], "925 Sterling Silver", "Gilded", 1199, 1499,
      "A polished silver heart on a fine chain. A timeless gift for someone you love - or for yourself."],
    ["green-beaded-silver-necklace", "Green Beaded Silver Necklace", "necklace", ["photo-1676329945867-01c9975aa9d1"], [C.silver, C.green], "Silver-Plated Alloy with Glass Beads", "Gilded", 999, null,
      "A silver necklace strung with fresh green beads. A bright, easy accessory for casual and festive looks."],
    ["gemstone-gold-bracelet", "Gemstone Gold Bracelet", "bracelet", ["photo-1717605383946-96c6884c36b4"], [C.gold, C.multi], "Gold-Plated Brass with Semi-Precious Stones", "Gilded", 1599, 1999,
      "A delicate gold bracelet set with four different colored stones. Wear it alone or stack it with bangles."],
    ["silver-heart-charm-bracelet", "Silver Heart Charm Bracelet", "bracelet", ["photo-1676291055501-286c48bb186f"], [C.silver, C.red], "925 Sterling Silver", "Gilded", 1399, null,
      "A silver bracelet with heart charms and two red accent stones. A sweet, meaningful gift."],
    ["evil-eye-bracelet", "Evil Eye Bracelet", "bracelet", ["photo-1721206624492-3d05631471ea"], [C.gold, C.blue], "Gold-Plated Alloy with Enamel", "Gilded", 799, 999,
      "A dainty bracelet with a protective evil-eye charm. Believed to bring good luck - and it looks lovely stacked."],
    ["retro-round-gold-sunglasses", "Retro Round Gold Sunglasses", "sunglasses", ["photo-1511499767150-a48a237f0083"], [C.gold], "Metal Frame, Polycarbonate Lenses", "Finish Line", 1299, 1699,
      "Retro round sunglasses with a thin gold metal frame. A vintage-inspired finish for summer looks."],
    ["classic-black-wayfarer-sunglasses", "Classic Black Wayfarer Sunglasses", "sunglasses", ["photo-1572635196237-14b3f281503f", "photo-1473496169904-658ba7c44d8a"], [C.black], "Acetate Frame, Polarized Lenses", "Finish Line", 1499, 1999,
      "The iconic black wayfarer shape that suits almost every face. Polarized lenses cut glare for driving and beach days."],
    ["ivory-frame-sunglasses", "Ivory Frame Sunglasses", "sunglasses", ["photo-1577803645773-f96470509666"], [C.ivory, C.brown], "Acetate Frame, Gradient Lenses", "Finish Line", 1399, null,
      "Chic white frames with warm brown gradient lenses. A fresh, fashion-forward pair for sunny days."],
    ["tortoiseshell-wayfarer-sunglasses", "Tortoiseshell Wayfarer Sunglasses", "sunglasses", ["photo-1559070081-648fb00b2ed1"], [C.brown], "Acetate Frame, Polarized Lenses", "Finish Line", 1599, 1999,
      "A timeless tortoiseshell wayfarer with polarized lenses. Comes with a hard case and cleaning cloth."],
    ["brown-leather-belt-silver-buckle", "Brown Leather Belt with Silver Buckle", "belt", ["photo-1624222247344-550fb60583dc"], [C.brown], "Genuine Leather", "Finish Line", 899, 1199,
      "A rich brown leather belt with a polished silver buckle. The finishing touch for jeans, chinos and dresses."],
    ["classic-black-leather-belt", "Classic Black Leather Belt", "belt", ["photo-1664286074176-5206ee5dc878", "photo-1664286074240-d7059e004dff"], [C.black], "Genuine Leather", "Finish Line", 899, null,
      "A simple, sleek black leather belt that goes with everything. Built to last with quality full-grain leather."],
    ["emerald-belt-golden-buckle", "Emerald Belt with Golden Buckle", "belt", ["photo-1752386223406-b3d94092d790"], [C.emerald, C.gold], "Vegan Leather", "Gilded", 999, 1299,
      "A bold emerald-green belt with a statement gold buckle. Cinch it over dresses or oversized shirts."],
    ["multicolor-silk-scarves-set", "Multicolor Silk Scarves Set", "scarf", ["photo-1545153252-0e2e698f0330"], [C.multi], "Silk Blend", "Gilded", 1499, 1999,
      "A set of vibrant silk-blend scarves in assorted colors. Tie them around your neck, hair or handbag for an instant style upgrade."],
    ["green-silk-scarf", "Green Silk Scarf", "scarf", ["photo-1643312892626-80632ef6d7dc"], [C.green], "Pure Silk", "Gilded", 1199, null,
      "A soft, fluid scarf in a rich green. Pure silk gives it a beautiful sheen and luxurious feel."],
    ["mustard-yellow-scarf", "Mustard Yellow Scarf", "scarf", ["photo-1677478863154-55ecce8c7536"], [C.mustard], "Wool Blend", "Gilded", 999, 1299,
      "A cozy mustard-yellow scarf that adds warmth and color to winter outfits."],
  ],
};
